#!/bin/bash

mkdir -p /root/.asgard

echo "Adding credentials for Nginx..."
echo $app_username":"$app_psw
echo $app_username":"$app_psw > /etc/nginx/.htpasswd
sed -i "s/asgardhost/$host/g" /etc/nginx/sites-available/asgard.conf


openssl genrsa -des3 -passout pass:yourpassword -out server.key 2048
openssl rsa -in server.key -out server.key.insecure -passin pass:yourpassword
mv server.key server.key.secure
mv server.key.insecure server.key

openssl req -new -key server.key -out server.csr -subj "/C=US/ST=CA/L=Los Gatos/O=Global Security/OU=IT OPS/CN=asgard.com"
openssl x509 -req -days 365  -in server.csr -signkey server.key -out server.crt

cp server.crt /etc/ssl/certs
cp server.key /etc/ssl/private

mkdir -p /var/log/nginx/log
touch /var/log/nginx/log/asgard.access.log
touch /var/log/nginx/log/asgard.error.log
ln -s /etc/nginx/sites-available/asgard.conf /etc/nginx/sites-enabled/asgard.conf
rm /etc/nginx/sites-enabled/default

echo "Starting nginx"
service nginx restart

export JAVA_OPTS=" \
      -verbose:sizes \
      -Xmx2g -Xms2g \
      -Xmn1g \
      -XX:MaxPermSize=256m \
      -XX:+HeapDumpOnOutOfMemoryError \
      -XX:-UseGCOverheadLimit \
      -XX:+ExplicitGCInvokesConcurrent \
      -XX:+PrintGCDateStamps -XX:+PrintGCDetails \
      -XX:+PrintTenuringDistribution \
      -XX:+CMSClassUnloadingEnabled \
      -XX:+UseConcMarkSweepGC \
"

java -jar /opt/asgard/asgard-standalone.jar >>/var/log/asgard.log
